name: BuildForOS

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      gist_id:
        required: true
        type: string
      build_type:
        required: false
        type: string
        default: Release

jobs:
  build-project:
    runs-on: ${{inputs.os}}
    outputs:
      badge_message: ${{ steps.set_variables.outputs.BADGE_MSG }}
      badge_color: ${{ steps.set_variables.outputs.BADGE_COLOR }}


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 #https://github.com/actions/checkout

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}}

      - name: Build
        id: build
        run: cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}}

      - name: SetVariables
        if: always()
        id: set_variables
        shell: bash
        run: |
          if [ ${{steps.build.outcome}} == 'success' ]; then
            echo "BADGE_MSG=passing" >> $GITHUB_OUTPUT
            echo "BADGE_COLOR=brightgreen" >> $GITHUB_OUTPUT
          else
            echo "BADGE_MSG=failed" >> $GITHUB_OUTPUT
            echo "BADGE_COLOR=red" >> $GITHUB_OUTPUT
          fi

  create-badge:
    needs: build-project
    runs-on: ubuntu-latest
    
    steps:
      - name: Create Badge
        if: always()
        uses: Tomiha/gist-write-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{secrets.GIST_BADGE_TOKEN}}
        with:
          gist_id: ${{inputs.gist_id}}
          file_name: badge.json
          content: '{ "schemaVersion": 1, "label": "${{inputs.os}}", "message": "${{needs.build-project.outputs.badge_message}}", "color": "${{needs.build-project.outputs.badge_color}}" }'