name: BuildAll

on:
 push:
  branches:
    - main

jobs:
  BuildAll:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            gist_id: aebe8917416c55e1318cdc4a11493dbd
          - os: windows-latest
            gist_id: ab416e989b92e560371af426493b9fa6

    uses: ./.github/workflows/build_for_os.yml
    with:
      os: ${{matrix.os}}
      gist_id: ${{matrix.gist_id}}