name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-project:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@V3

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2 #https://github.com/marketplace/actions/actions-setup-cmake
        with:
          cmake-version: '3.20.x'

      - name: Test Cmake
        run: cmake --version