#https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CI

on:
  push:
    branches-ignore:
      - main
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

env:
  BUILD_TYPE: Release

jobs:
  build-project:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 #https://github.com/actions/checkout

      #CMake is already part of the runner :) (v3.30.5)
      # - name: Install CMake
      #   uses: jwlawson/actions-setup-cmake@v2 #https://github.com/marketplace/actions/actions-setup-cmake
      #   with:
      #     cmake-version: '3.20.x'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}