name: update-gist-test

on:
  push:
    branches:
      - main


jobs:
  deploy-to-gist:
    runs-on: ubuntu-latest

    steps:
      - name: log-secret
        env:
          GIST_TOKEN: ${{secrets.GIST_BADGE_TOKEN}}
        run: |
          echo $GIST_TOKEN
          echo "$GIST_TOKEN"
          echo ${secrets.GIST_BADGE_TOKEN}
      # - name: deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GIST_BADGE_TOKEN }}
      #   uses: sergeysova/gist-write-action@v1
      #   with:
      #     gist_id: 55955be55ba7293e21dff41424dc3ccc
      #     file_name: badge.json
      #     content: "{}"