name: update-gist-test

on:
  push:
    branches-ignore:
      - main


jobs:
  deploy-to-gist:
    runs-on: ubuntu-latest

    steps:
        - name: Create Awesome Badge
          uses: schneegans/dynamic-badges-action@v1.7.0
          with:
            auth: ${{secrets.GIST_BADGE_TOKEN}}
            gistID: 55955be55ba7293e21dff41424dc3ccc
            filename: badge.json
            label: ubuntu
            message: Fail
            color: red
            namedLogo: ubuntu
            logoColor: f5f5f5